### ISSUE TITLE
Java file

### ISSUE THREAD

**Issue by sandip-narwade** [PialKanti/Online-Banking-System#1]
Hello Sir, I need a your code with DB

sandipnd31@gmail.com

**Comment by PialKanti** [comment]
I have uploaded my [database sql files](https://github.com/PialKanti/Online-Banking-System/tree/master/database_files). You can import this files to your database.

**Comment by sandip-narwade** [comment]
@PialKanti  thanku

**Comment by PialKanti** [comment]
Welcome
